name: airflow
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - feast_network

  airflow-webserver:
    image: apache/airflow:2.9.3-python3.11
    container_name: airflow-webserver
    entrypoint: /bin/bash
    command: >
      -c "pip install 'feast[redis,postgres]' && exec airflow webserver"
    ports:
      - "8081:8080"
    environment:
      - AIRFLOW_HOME=/opt/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__FERNET_KEY=wmSpjmCJ477jqpJE9BlzuzzI_Cw4P4RRGBZj1KeAPcU=
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://user:password@postgres/postgres
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=True
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__SECRET_KEY=some-secret
    volumes:
      - /home/cc/feast-artifact/dags:/opt/airflow/dags
      - /home/cc/feast-artifact/workspace/feature_repo:/opt/airflow/feature_repo
      - airflow_shared:/opt/airflow
    depends_on:
      airflow-setup:
        condition: service_completed_successfully
    networks:
      - feast_network

  airflow-scheduler:
    image: apache/airflow:2.9.3-python3.11
    container_name: airflow-scheduler
    entrypoint: /bin/bash
    command: >
      -c "pip install 'feast[redis,postgres]' && exec airflow scheduler"
    environment:
      - AIRFLOW_HOME=/opt/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__FERNET_KEY=wmSpjmCJ477jqpJE9BlzuzzI_Cw4P4RRGBZj1KeAPcU=
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://user:password@postgres/postgres
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - /home/cc/feast-artifact/dags:/opt/airflow/dags
      - /home/cc/feast-artifact/workspace/feature_repo:/opt/airflow/feature_repo
      - airflow_shared:/opt/airflow
    depends_on:
      airflow-setup:
        condition: service_completed_successfully
    networks:
      - feast_network

  airflow-setup:
    image: apache/airflow:2.9.3-python3.11
    container_name: airflow-setup
    entrypoint: /bin/bash
    command: >
      -c "pip install 'feast[redis,postgres]' && airflow db migrate && airflow users create --username admin --firstname Airflow --lastname Admin --role Admin --email airflow@example.com --password airflow"
    environment:
      - AIRFLOW_HOME=/opt/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__FERNET_KEY=wmSpjmCJ477jqpJE9BlzuzzI_Cw4P4RRGBZj1KeAPcU=
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://user:password@postgres/postgres
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - /home/cc/feast-artifact/dags:/opt/airflow/dags
      - /home/cc/feast-artifact/workspace/feature_repo:/opt/airflow/feature_repo
      - airflow_shared:/opt/airflow
    networks:
      - feast_network
    restart: "no"

volumes:
  airflow_shared:
  postgres_data:

networks:
  feast_network:
    external: true