services:
  
  minio:
    image: minio/minio:RELEASE.2023-12-14T18-51-57Z
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "minio_user"
      MINIO_ROOT_PASSWORD: "minio_password"
    healthcheck:
      test: ["CMD", "/usr/bin/minio", "--version"]
      interval: 5s
      timeout: 10s
      retries: 10
    command: server /data --console-address ":9001"
  